# Generated by Django 2.2 on 2021-03-21 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='desc',
            field=models.TextField(default='programming'),
        ),
    ]
