# Generated by Django 2.2 on 2021-03-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_author', '0002_book_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.CharField(default='Author for different books', max_length=255),
        ),
    ]
